version: "3"
volumes:
  node_modules:
services:
  sudoku-preact-rxjs:
    build: .devcontainer
    container_name: sudoku-preact-rxjs
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
      - 8080:8080
